local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fgt", builtin.git_files, { desc = "Telescope git files" })
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Telescope help tags" })
vim.keymap.set("n", "gr", ":Telescope lsp_references<CR>", { noremap = true })
vim.keymap.set("n", "gi", ":Telescope lsp_implementations<CR>", { noremap = true })
vim.keymap.set("n", "<leader>jq", ":%!jq .<CR>", {noremap = true, desc = "jq format json file"})
